name: Telegram Notify [deploy]

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Build project
        run: |
          echo "Building project..."
          sleep 5  # Эмуляция сборки
          echo "Build successful!"

      - name: Notify on success
        if: success()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            "✅ Сборка успешна! 🎉 \n🔗 [Коммит](${{ github.event.head_commit.url }})"
          parse_mode: "markdown"

      - name: Notify on failure
        if: failure()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            "❌ Ошибка сборки! Проверьте логи. \n🔗 [Коммит](${{ github.event.head_commit.url }})"
          parse_mode: "markdown"
